application_port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "users"
argon:
  variant: "Argon2id"
  iterations: 2
  parallelism: 1
  memory: 19456
